import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/sidebar";

const inter = Inter({ 
    subsets: ["latin", "cyrillic-ext", "greek", "vietnamese"],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className={'bg-background text-white min-h-screen flex'}>
                    <Sidebar />

                    <div
                    className={'w-full rounded-xl p-main-padding'}
                    >
                        {children}
                    </div>
                    
                </div>
                
            </body>
        </html>
    );
}
